apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opw.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "opw.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ tpl (toYaml .Values.config) . | sha256sum }}
data:
  {{- if .Values.config }}
  config.yaml: {{ tpl (toYaml .Values.config) . | nindent 4 }}
  {{- else }}
{{ fail "A `config` must be specified, see https://github.com/DataDog/helm-charts/tree/main/examples/observability-pipelines-worker for examples" }}
  {{- end -}}
