{{- if and .Values.datadog.configKey (not .Values.datadog.configKeyExistingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opw.configKeySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "opw.labels" . | nindent 4 }}
type: Opaque
data:
  config-key: {{ default "MISSING" .Values.datadog.configKey | b64enc | quote }}
{{- end -}}
