{{- if .Values.datadog.bootstrap.secretFileContents }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opw.fullname" . }}-secret-file-backend
  namespace: {{ .Release.Namespace }}
  labels: {{ include "opw.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.json: |
    {{- toJson (.Values.datadog.bootstrap.secretFileContents | default dict) | nindent 4 }}
{{- end }}
