{{- $secretFile := .Values.bootstrapBackend.secretFile | default dict }}

{{- if $secretFile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opw.fullname" . }}-secret-file-backend
type: Opaque
stringData:
  secrets.json: |
    {{- toJson ($secretFile.entries | default dict) | nindent 4 }}
{{- end }}
