apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "opw.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "opw.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  selector:
    matchLabels: {{ include "opw.template-labels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  updateStrategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  serviceName: {{ template "opw.fullname" . }}-headless
  template:
    metadata:
      labels: {{ include "opw.template-labels" . | nindent 8 }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
      annotations:
        checksum/bootstrap: {{ include (print .Template.BasePath "/bootstrap.yaml") . | sha256sum }}
        checksum/secret-file-backend: {{ include (print .Template.BasePath "/secret-file-backend.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
{{ tpl (toYaml .Values.podAnnotations) . | indent 8 }}
        {{- end }}
    spec: {{ include "opw.pod" . | nindent 6 }}
  volumeClaimTemplates:
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  - metadata:
      name: data
      annotations:
        {{- if .Values.persistence.annotations }}
{{ toYaml .Values.persistence.annotations | nindent 8 }}
        {{- end }}
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.retentionPolicy }}
      persistentVolumeClaimRetentionPolicy:
        {{- toYaml .Values.persistence.retentionPolicy | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.selector }}
      selector: {{ toYaml .Values.persistence.selector | nindent 8 }}
      {{- end }}
{{- end }}
