# Test values for full observability setup - APM, Logs, Process, Events, KSM

operator:
  image:
    tag: 1.22.0
  # datadogCRDs:
  #   keepCrds: true

datadog:
  operator:
    enabled: true   # default is true

    # migration:
    #   preview: true
    #   enabled: true

  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  kubelet:
    tlsVerify: false
  site: datad0g.com
  clusterName: helm-migration-standard
  logLevel: INFO
  tags:
    - "env:staging"
    - "team:agent-onboarding"
  
  # APM
  apm:
    socketEnabled: true
  
  # Logs
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    autoMultiLineDetection: true
  
  # Dogstatsd
  dogstatsd:
    useSocketVolume: true
    originDetection: true
    tagCardinality: orchestrator
  
  # Process
  processAgent:
    processCollection: true
    containerCollection: true
    processDiscovery: true
  
  # Events
  collectEvents: true
  kubernetesEvents:
    unbundleEvents: true
  
  # Orchestrator Explorer
  orchestratorExplorer:
    enabled: true
    container_scrubbing:
      enabled: true
  
  # KSM Core
  kubeStateMetricsCore:
    enabled: true
  
  # Prometheus Scrape
  prometheusScrape:
    enabled: true
    serviceEndpoints: true

agents:
  image:
    tag: 7.75.0

clusterAgent:
  image:
    tag: 7.75.0
  enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: true

clusterChecksRunner:
  enabled: true
  image:
    tag: 7.75.0
    