{{- define "default-agent-container-resources" }}
requests:
  cpu: 200m
  memory: 256Mi
limits:
  cpu: 200m
  memory: 256Mi
  {{- if .Values.datadog.useVSock }}
  squat.ai/vsock: 1
  {{- end }}
{{- end }}

{{- define "default-system-probe-container-resources" }}
requests:
  cpu: 100m
  memory: 400Mi
limits:
  cpu: 100m
  memory: 400Mi
  {{- if .Values.datadog.useVSock }}
  squat.ai/vsock: 1
  {{- end }}
{{- end }}

{{- define "default-container-resources" }}
requests:
  cpu: 100m
  memory: 200Mi
limits:
  cpu: 100m
  memory: 200Mi
  {{- if .Values.datadog.useVSock }}
  squat.ai/vsock: 1
  {{- end }}
{{- end }}

{{- define "default-cluster-check-runner-resources" }}
requests:
  cpu: 200m
  memory: 500Mi
limits:
  cpu: 200m
  memory: 500Mi
  {{- if .Values.datadog.useVSock }}
  squat.ai/vsock: 1
  {{- end }}
{{- end }}
