{{- define "daemonset-volumes-linux" -}}
- name: logdatadog
  emptyDir: {}
- name: tmpdir
  emptyDir: {}
- hostPath:
    path: /proc
  name: procdir
- hostPath:
    path: /sys/fs/cgroup
  name: cgroups
{{- if and (not .Values.providers.gke.autopilot) (or .Values.datadog.systemProbe.osReleasePath .Values.datadog.osReleasePath) }}
- hostPath:
    path: {{ .Values.datadog.systemProbe.osReleasePath | default .Values.datadog.osReleasePath }}
  name: os-release-file
{{- end }}
{{- if eq (include "should-enable-system-probe" .) "true" }}
{{- if .Values.datadog.systemProbe.enableDefaultOsReleasePaths }}
- hostPath:
    path: /etc/redhat-release
  name: etc-redhat-release
- hostPath:
    path: /etc/fedora-release
  name: etc-fedora-release
- hostPath:
    path: /etc/lsb-release
  name: etc-lsb-release
{{- end }}
{{- end -}}
{{- if eq (include "should-enable-fips" .) "true" }}
- name: fips-config
  configMap:
    name: {{ template "datadog.fullname" . }}-fips-config
{{- end }}
{{- if eq (include "should-mount-hostPath-for-dsd-socket" .) "true" }}
- hostPath:
    path: {{ .Values.datadog.dogstatsd.hostSocketPath }}
    type: DirectoryOrCreate
  name: dsdsocket
{{- else }}
- emptyDir: {}
  name: dsdsocket
{{- end }}
{{- if .Values.providers.eks.ec2.useHostnameFromFile }}
- hostPath:
    path: /var/lib/cloud/data/instance-id
    type: File
  name: cloudinit-instance-id-file
{{- end }}
{{- if .Values.datadog.kubelet.hostCAPath }}
- hostPath:
    path: {{ .Values.datadog.kubelet.hostCAPath }}
    type: File
  name: kubelet-ca
{{- end }}
{{- if eq (include "trace-agent-use-uds" .) "true" }}
- hostPath:
    path: {{ .Values.datadog.apm.hostSocketPath }}
    type: DirectoryOrCreate
  name: apmsocket
{{- end }}
- name: s6-run
  emptyDir: {}
{{- if (or (.Values.datadog.confd) (.Values.datadog.autoconf)) }}
- name: confd
  configMap:
    name: {{ include "agents.confd-configmap-name" . }}
{{- end }}
{{- if eq (include "should-enable-system-probe" .) "true" }}
- name: sysprobe-config
  configMap:
    name: {{ template "datadog.fullname" . }}-system-probe-config
{{- if eq .Values.datadog.systemProbe.seccomp "localhost/system-probe" }}
- name: datadog-agent-security
  configMap:
    name: {{ template "datadog.fullname" . }}-security
- hostPath:
    path: {{ .Values.datadog.systemProbe.seccompRoot }}
  name: seccomp-root
{{- end }}
- hostPath:
    path: /sys/kernel/debug
  name: debugfs
- name: sysprobe-socket-dir
  emptyDir: {}
{{- if and (eq (include "runtime-compilation-enabled" .) "true") .Values.datadog.systemProbe.enableDefaultKernelHeadersPaths }}
- hostPath:
    path: /lib/modules
  name: modules
{{- if eq (include "can-mount-host-usr-src" .) "false" }}
- hostPath:
    path: /usr/src
  name: src
{{- end }}
{{- end }}
{{- if eq (include "runtime-compilation-enabled" .) "true" }}
- hostPath:
    path: {{ .Values.datadog.systemProbe.runtimeCompilationAssetDir }}/build
    type: DirectoryOrCreate
  name: runtime-compiler-output-dir
- hostPath:
    path: {{ .Values.datadog.systemProbe.runtimeCompilationAssetDir }}/kernel-headers
    type: DirectoryOrCreate
  name: kernel-headers-download-dir
{{- if not .Values.datadog.systemProbe.mountPackageManagementDirs }}
- hostPath:
    path: /etc/apt
  name: apt-config-dir
- hostPath:
    path: /etc/yum.repos.d
  name: yum-repos-dir
- hostPath:
    path: /etc/zypp
  name: opensuse-repos-dir
- hostPath:
    path: /etc/pki
  name: public-key-dir
- hostPath:
    path: /etc/yum/vars
  name: yum-vars-dir
- hostPath:
    path: /etc/dnf/vars
  name: dnf-vars-dir
- hostPath:
    path: /etc/rhsm
  name: rhel-subscription-dir
{{- else }}
{{- range .Values.datadog.systemProbe.mountPackageManagementDirs }}
- hostPath:
    path: {{ .hostPath }}
  name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.datadog.systemProbe.btfPath }}
- hostPath:
    path: {{ .Values.datadog.systemProbe.btfPath }}
  name: btf-path
{{- end }}
{{- end }}
{{- if or .Values.datadog.processAgent.enabled (eq (include "should-enable-system-probe" .) "true") (eq (include "should-enable-security-agent" .) "true") }}
- hostPath:
    path: /etc/passwd
  name: passwd
{{- end }}
{{- if or (and (eq (include "should-enable-system-probe" .) "true") .Values.datadog.serviceMonitoring.enabled) (and (eq (include "should-enable-security-agent" .) "true") .Values.datadog.securityAgent.compliance.enabled) }}
- hostPath:
    path: /
  name: hostroot
{{- end }}
{{- if eq  (include "should-enable-security-agent" .) "true" }}
{{- if .Values.datadog.securityAgent.compliance.enabled }}
- hostPath:
    path: /etc/group
  name: group
{{- if .Values.datadog.securityAgent.compliance.configMap }}
- name: complianceconfigdir
  configMap:
    name: {{ .Values.datadog.securityAgent.compliance.configMap }}
{{- end }}
{{- end }}
{{- if and (or .Values.datadog.securityAgent.runtime.enabled .Values.datadog.securityAgent.runtime.fimEnabled) .Values.datadog.securityAgent.runtime.policies.configMap }}
- name: runtimepoliciesdir
  configMap:
    name: {{ .Values.datadog.securityAgent.runtime.policies.configMap }}
{{- end }}
{{- end }}
{{- if or .Values.datadog.logs.enabled .Values.datadog.logsEnabled }}
- hostPath:
    path: {{ template "datadog.hostMountRoot" . }}/logs
  name: pointerdir
- hostPath:
    path: {{ .Values.datadog.kubelet.podLogsPath | default "/var/log/pods" }}
  name: logpodpath
- hostPath:
    path: /var/log/containers
  name: logscontainerspath
{{- if not .Values.datadog.criSocketPath }}
- hostPath:
    path: /var/lib/docker/containers
  name: logdockercontainerpath
{{- end }}
{{- end }}
{{- if .Values.datadog.containerRuntimeSupport.enabled }}
- hostPath:
    path: {{ dir (include "datadog.dockerOrCriSocketPath" .) }}
  name: runtimesocketdir
{{- end }}
{{- end -}}
