{{- if and (eq (include "should-deploy-cluster-agent" .) "true") .Values.clusterAgent.rbac.create -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-cluster-agent
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - namespaces
  - componentstatuses
  - limitranges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups: ["quota.openshift.io"]
  resources:
  - clusterresourcequotas
  verbs:
  - get
  - list
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
{{- if .Values.datadog.collectEvents }}
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - {{ template "datadog.fullname" . }}token  # Kubernetes event collection state
  - datadogtoken  # Kept for backward compatibility with agent <7.37.0
  verbs:
  - get
  - update
{{- end }}
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - {{ template "datadog.fullname" . }}-leader-election  # Leader election token
  - datadog-leader-election  # Kept for backward compatibility with agent <7.37.0
{{- if .Values.clusterAgent.metricsProvider.enabled }}
  - datadog-custom-metrics
{{- end }}
  verbs:
  - get
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  resourceNames:
  - {{ template "datadog.fullname" . }}-leader-election  # Leader election token
  verbs:
  - get
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
{{- if .Values.clusterAgent.metricsProvider.enabled }}
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - extension-apiserver-authentication
  verbs:
  - get
  - list
  - watch
{{- end }}
- apiGroups:  # To create the leader election token and hpa events
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
- nonResourceURLs:
  - "/version"
  - "/healthz"
  verbs:
  - get
{{- if and .Values.clusterAgent.metricsProvider.enabled .Values.clusterAgent.metricsProvider.wpaController }}
- apiGroups:
  - "datadoghq.com"
  resources:
  - "watermarkpodautoscalers"
  verbs:
  - "list"
  - "get"
  - "watch"
{{- end }}
{{- if and .Values.datadog.apm.instrumentation.enabled .Values.datadog.apm.instrumentation.language_detection.enabled }}
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - list
  - get
  - watch
  - patch
{{- end }}
{{- if eq (include "should-enable-k8s-resource-monitoring" .) "true" }}
- apiGroups:  # to get the kube-system namespace UID and generate a cluster ID
  - ""
  resources:
  - namespaces
  resourceNames:
  - "kube-system"
  verbs:
  - get
- apiGroups:  # To create the cluster-id configmap
  - ""
  resources:
  - configmaps
  resourceNames:
  - "datadog-cluster-id"
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  - persistentvolumeclaims
  - serviceaccounts
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - list
  - get
  - watch
{{- if .Values.clusterAgent.admissionController.remoteInstrumentation.enabled }}
  - patch
{{- end }}
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  - jobs
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "storage.k8s.io"
  resources:
  - storageclasses
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  verbs:
  - list
  - get
  - watch
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - list
    - get
    - watch
{{- end }}
{{- if and .Values.clusterAgent.metricsProvider.enabled .Values.clusterAgent.metricsProvider.useDatadogMetrics }}
- apiGroups:
  - "datadoghq.com"
  resources:
  - "datadogmetrics"
  verbs:
  - "list"
  - "create"
  - "delete"
  - "watch"
- apiGroups:
  - "datadoghq.com"
  resources:
  - "datadogmetrics/status"
  verbs:
  - "update"
{{- end }}
{{- if .Values.clusterAgent.admissionController.enabled }}
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  resourceNames:
    - {{ .Values.clusterAgent.admissionController.webhookName | quote }}
  verbs: ["get", "list", "watch", "update"]
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "replicasets", "deployments", "daemonsets"]
  verbs: ["get"]
{{- end }}
{{- if eq  (include "should-enable-security-agent" .) "true" }}
{{- if .Values.datadog.securityAgent.compliance.enabled }}
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - namespaces
  verbs:
  - list
- apiGroups:
  - "policy"
  resources:
  - poddisruptionbudgets
  {{- if and .Values.clusterAgent.podSecurity.podSecurityPolicy.create (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
  - podsecuritypolicies
  {{- end }}
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - list
{{- end }}
{{- end }}
{{- if and .Values.clusterAgent.podSecurity.podSecurityPolicy.create (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - {{ template "datadog.fullname" . }}-cluster-agent
{{- end }}
- apiGroups:
  - "security.openshift.io"
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - {{ template "datadog.fullname" . }}-cluster-agent
  - hostnetwork
{{- if eq (include "need-secret-permissions" .) "true" }}
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
{{- end }}
{{- if .Values.datadog.orchestratorExplorer.enabled }}
{{- include "orchestratorExplorer-config-crs" . }}
{{- end }}
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-cluster-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "datadog.fullname" . }}-cluster-agent
subjects:
  - kind: ServiceAccount
    name: {{ template "datadog.fullname" . }}-cluster-agent
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.clusterAgent.rbac.automountServiceAccountToken }}
metadata:
  labels:
    app: "{{ template "datadog.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
{{ include "datadog.labels" . | indent 4 }}
{{- if .Values.clusterAgent.rbac.serviceAccountAnnotations }}
  annotations: {{ tpl (toYaml .Values.clusterAgent.rbac.serviceAccountAnnotations) . | nindent 4}}
{{- end }}
  name: {{ template "datadog.fullname" . }}-cluster-agent
  namespace: {{ .Release.Namespace }}
{{- if .Values.clusterAgent.admissionController.enabled }}
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-cluster-agent-main
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "create"]
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: "{{ template "datadog.fullname" . }}-cluster-agent-main"
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "datadog.fullname" . }}-cluster-agent-main
subjects:
  - kind: ServiceAccount
    name: {{ template "datadog.fullname" . }}-cluster-agent
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}

{{- if and (eq (include "should-deploy-cluster-agent" .) "true") .Values.clusterAgent.rbac.create .Values.clusterAgent.metricsProvider.enabled }}
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    app: "{{ template "datadog.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-cluster-agent-system-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ template "datadog.fullname" . }}-cluster-agent
    namespace: {{ .Release.Namespace }}
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: "{{ template "datadog.fullname" . }}-cluster-agent-apiserver"
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: {{ template "datadog.fullname" . }}-cluster-agent
    namespace: {{ .Release.Namespace }}
{{- end -}}

{{- if (((.Values.datadog.autoscaling).workload).enabled) }}
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-cluster-agent-autoscaling
  namespace: {{ .Release.Namespace }}
rules:
# Access to own CRD
- apiGroups:
  - "datadoghq.com"
  resources:
  - "datadogpodautoscalers"
  - "datadogpodautoscalers/status"
  verbs:
  - "*"
# Scale subresource for all resources
- apiGroups:
  - "*"
  resources:
  - "*/scale"
  verbs:
  - 'update'
  - 'get'
# Ability to generate events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
# Patching POD to add annotations. TODO: Remove when we have a better way to generate single event
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
# Triggering rollout on Deployments
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - patch
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-cluster-agent-autoscaling
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "datadog.fullname" . }}-cluster-agent-autoscaling
subjects:
  - kind: ServiceAccount
    name: {{ template "datadog.fullname" . }}-cluster-agent
    namespace: {{ .Release.Namespace }}
{{- end}}

{{- if or .Values.datadog.kubernetesResourcesAnnotationsAsTags .Values.datadog.kubernetesResourcesLabelsAsTags}}
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-cluster-agent-annotations-and-labels-as-tags
  namespace: {{ .Release.Namespace }}

{{- $groupedResources := dict }}
{{- $mergedResources := merge (default dict .Values.datadog.kubernetesResourcesAnnotationsAsTags) (default dict .Values.datadog.kubernetesResourcesLabelsAsTags)}}
{{- range $resource, $labels := $mergedResources }}
  {{- $parts := split "." $resource }}
  {{- $apiGroup := "" }}
  {{- $resourceName := $resource }}
  {{- if eq (len $parts) 2 }}
    {{- $apiGroup = index $parts "_1" }}
    {{- $resourceName = index $parts "_0" }}
  {{- end }}
  {{- $existing := index $groupedResources $apiGroup | default (list) }}
  {{- $groupedResources = set $groupedResources $apiGroup (append $existing $resourceName) }}
{{- end }}

rules:

# Iterate through the apiGroups and create rules for each resource
{{- range $apiGroup, $resources := $groupedResources }}
- apiGroups:
  - "{{ $apiGroup }}"
  resources:
  {{- range $resource := $resources }}
  - {{ $resource }}
  {{- end }}
  verbs:
  - get
  - list
  - watch
{{- end }}

---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "datadog.labels" . | indent 4 }}
  name: {{ template "datadog.fullname" . }}-cluster-agent-annotations-and-labels-as-tags
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "datadog.fullname" . }}-cluster-agent-annotations-and-labels-as-tags
subjects:
  - kind: ServiceAccount
    name: {{ template "datadog.fullname" . }}-cluster-agent
    namespace: {{ .Release.Namespace }}
{{- end -}}