apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "datadog.fullname" . }}-endpoint-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
    datadog.com/config-type: endpoint-config
data:
  api-key-secret-name: {{ default "" ( include "datadog.apiSecretName" . ) }}
{{- if or .Values.datadog.appKey .Values.datadog.appKeyExistingSecret }}
  app-key-secret-name: {{ default "" ( include "datadog.appKeySecretName" . )  }}
{{- end }}
{{- if .Values.datadog.site }}
  dd-site: {{ .Values.datadog.site  | quote }}
{{- end }}
{{- if .Values.datadog.dd_url }}
  dd-url: {{ .Values.datadog.dd_url | quote }}
{{- end }}
