apiVersion: v1
kind: Secret
metadata:
  name: datadog-meta-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
{{- if .Values.datadog.secretAnnotations }}
  annotations: {{ toYaml .Values.datadog.secretAnnotations | nindent 4 }}
{{- end }}
type: Opaque
data:
  api-key-secret-name: {{ default "" ( include "datadog.apiSecretName" . ) | b64enc | quote }}
  app-key-secret-name: {{ default "" ( include "datadog.appKeySecretName" . ) | b64enc | quote }}
{{- if .Values.datadog.site }}
  dd-site: {{ .Values.datadog.site | b64enc | quote }}
{{- end }}
{{- if .Values.datadog.dd_url }}
  dd-url: {{ .Values.datadog.dd_url | b64enc | quote }}
{{- end }}