{{- if not .Values.clusterAgent.tokenExistingSecret }}
{{- if eq (include "should-deploy-cluster-agent" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clusterAgent.tokenSecretName" . }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: "{{ template "datadog.fullname" . }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
data:
  {{ if .Values.clusterAgent.token -}}
  token: {{ .Values.clusterAgent.token | b64enc | quote }}
  {{ else -}}
  token: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
{{- end }}
{{ end }}