{{- if and (not .Values.datadog.appKeyExistingSecret) .Values.datadog.appKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "datadog.appKeySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
{{- if .Values.datadog.secretAnnotations }}
  annotations: {{ toYaml .Values.datadog.secretAnnotations | nindent 4 }}
{{- end }}
type: Opaque
data:
  app-key: {{ .Values.datadog.appKey | b64enc | quote }}
{{- end }}
