apiVersion: v1
kind: Secret
metadata:
  name: secret-creds-meta
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
{{- if .Values.datadog.secretAnnotations }}
  annotations: {{ toYaml .Values.datadog.secretAnnotations | nindent 4 }}
{{- end }}
type: Opaque
data:
  api-key-secret-name: {{ default "MISSING" ( include "datadog.apiSecretName" . ) | b64enc | quote }}
  app-key-secret-name: {{ default "MISSING" ( include "datadog.appKeySecretName" . ) | b64enc | quote }}
