{{- if and .Values.apiKey (not .Values.apiKeyExistingSecret) (include "is-valid-endpoint-config-data" (list . "api-key")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "datadog-operator.apiKeySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "datadog-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | b64enc | quote }}
{{- end }}
