{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "datadog-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 | }}
{{- end }}
  labels:
{{ include "datadog-operator.labels" . | indent 4 }}
{{- if eq .Values.serviceAccount.automountServiceAccountToken false }}
automountServiceAccountToken: false
{{- end }}
{{- end -}}
