apiVersion: v2
name: private-action-runner
description: A Helm chart to deploy the private action runner

type: application
version: 0.14.0
appVersion: "1.22.0"
keywords:
- app builder
- workflow automation
home: https://www.datadoghq.com
icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
sources:
- https://docs.datadoghq.com/service_management/workflows/private_actions
- https://app.datadoghq.com/app-builder/private-action-runners
maintainers:
- name: Datadog
  email: support@datadoghq.com
