{{- if not .Values.configConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synthetics-private-location.fullname" . }}-config
  labels:
    {{- include "synthetics-private-location.labels" . | nindent 4 }}
data:
  synthetics-check-runner.json: |-
{{ .Values.configFile | indent 4 }}
---
{{- end }}

