image:
  tag: nightly
  pullPolicy: Always

datadog:
  pipelineId: "8799b5cc-c2c9-4be5-9660-f97a4eede7f7"
  workerAPI:
    enabled: true
    playground: false
    address: "127.0.0.1:1010"

args:
  - run
  - --skip-key-validation
