image:
  tag: nightly
  pullPolicy: Always

datadog:
  pipelineId: "8799b5cc-c2c9-4be5-9660-f97a4eede7f7"
args:
  - run
  - --skip-key-validation
service:
  enabled: true
serviceHeadless:
  enabled: false
