{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "datadog-csi-driver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datadog-csi-driver.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "get"]
{{- end }}

