{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datadog-csi-driver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datadog-csi-driver.labels" . | nindent 4 }}
{{- end }}

