datadog:
  apiKey: "00000000000000000000000000000000"
agents:
  enabled: true
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "sleep 70"]

operator:
  datadogSLO:
    enabled: false
  datadogGenericResource:
    enabled: false
