datadog:
  apiKey: "00000000000000000000000000000000"
agents:
  enabled: true
  terminationGracePeriodSeconds: 90

operator:
  datadogSLO:
    enabled: false
  datadogGenericResource:
    enabled: false
