datadog:
  apiKey: "00000000000000000000000000000000"
  appKey: "0000000000000000000000000000000000000000"
  kubelet:
    tlsVerify: false
  site: datadoghq.eu
  sbom:
    containerImage:
      enabled: true
      uncompressedLayersSupport: true

operator:
  datadogSLO:
    enabled: false
  datadogGenericResource:
    enabled: false
