datadog:
  apiKey: "00000000000000000000000000000000"
  appKey: "0000000000000000000000000000000000000000"
  kubelet:
    tlsVerify: false
  appsec:
    injector:
      enabled: true
      autoDetect: true
      processor:
        port: 443
        service:
          name: "appsec-processor"
          namespace: "datadog"
clusterAgent:
  enabled: true
