# Empty values file for testing default parameters.
# Exception for kubelet.tlsVerify, which is set to true by default. We set it to false here to avoid TLS verification on kind clusters used by CI.
datadog:
  apiKey: "00000000000000000000000000000000"
  appKey: "0000000000000000000000000000000000000000"
  kubelet:
    tlsVerify: false

clusterAgent:
  confd:
    tcp_check.yaml: |-
      init_config:
      instances:
        - name: "healthPort"
          port: "5556"
