datadog:
  kubelet:
    tlsVerify: false
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true

operator:
  datadogSLO:
    enabled: false
  datadogGenericResource:
    enabled: false
