# Default values for datadog-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

crds:
  # crds.datadogMetrics -- Set to true to deploy the DatadogMetrics CRD
  datadogMetrics: false
  # crds.datadogAgents -- Set to true to deploy the DatadogAgents CRD
  datadogAgents: false
  # crds.datadogMonitors -- Set to true to deploy the DatadogMonitors CRD
  datadogMonitors: false
  # crds.datadogSLOs -- Set to true to deploy the DatadogSLO CRD
  datadogSLOs: false
  # crds.datadogAgentProfiles -- Set to true to deploy the DatadogAgentProfiles CRD
  datadogAgentProfiles: false
  # crds.datadogPodAutoscalers -- Set to true to deploy the DatadogPodAutoscalers CRD
  datadogPodAutoscalers: false
  # crds.datadogDashboards -- Set to true to deploy the DatadogDashboards CRD
  datadogDashboards: false
  # crds.datadogGenericResources -- Set to true to deploy the DatadogGenericResources CRD
  datadogGenericResources: false
  # crds.datadogAgentInternals -- Set to true to deploy the DatadogAgentInternals CRD
  datadogAgentInternals: false

# keepCrds -- Instruct Helm to skip deleting CRD resources when a helm operation (such as helm uninstall, helm upgrade or helm rollback) would result in its deletion. These resources will become orphaned unless another Helm installation is instructed to take ownership of the resources using the `--take-ownership` flag.
# For more details: https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource
keepCrds:

# nameOverride -- Override name of app
nameOverride: ""

# fullnameOverride -- Override the fully qualified app name
fullnameOverride: ""
