apiVersion: v2
name: synthetics-private-location
version: 0.15.6
appVersion: 1.31.0
description: Datadog Synthetics Private Location
keywords:
- monitoring
- synthetics
home: https://www.datadoghq.com
icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
sources:
- https://docs.datadoghq.com/synthetics/private_locations
- https://app.datadoghq.com/synthetics/settings/private-locations
maintainers:
- name: Datadog
  email: support@datadoghq.com
